steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - functions
      - deploy
      - pubsubtobq
      - '--runtime=python39'
      - '--trigger-http'
      - '--source=pluto/cloudfunction'
      - '--entry-point=pubsub_to_bigquery'
      - '--region=us-central1'
options:
  logging: CLOUD_LOGGING_ONLY
